/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opt_course_ex_OpCourseEx */

#ifndef _Included_com_example_opt_course_ex_OpCourseEx
#define _Included_com_example_opt_course_ex_OpCourseEx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opt_course_ex_OpCourseEx
 * Method:    thinning
 * Signature: (JJ)V
 */
JNIEXPORT double JNICALL Java_com_example_opt_1course_1ex_OpCourseEx_thinning
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
